

--  run in this order only 

-- DELETE COMMAND FOR DEV
DELETE FROM SOCIAL_LINKS;
DELETE  FROM  BLOG_IMAGES;
DELETE FROM FOLLOWERS;
DELETE FROM BLOG_COMMENTS;
DELETE FROM BLOG_LIKES;
DELETE FROM BLOGS;
DELETE FROM USERS;