

-- using database DEV
USE DEV;




-- To get user details 
CREATE VIEW USER_PROFILE AS
SELECT 
  U.NAME AS 'NAME', 
  U.EMAIL AS 'EMAIL',
  U.WORK_TYPE AS 'WORK_TYPE',
  U.BIO AS 'BIO',
  U.PROFILE_PIC AS 'PROFILE_PIC',
  COUNT(DISTINCT F1.FOLLOWER_EMAIL) AS 'FOLLOWED_BY',  
  COUNT(DISTINCT F2.USER_EMAIL) AS 'FOLLOWING',        
  GROUP_CONCAT(DISTINCT S.LINK) AS 'LINKS'
FROM 
  USERS U
  LEFT JOIN FOLLOWERS F1 ON U.EMAIL = F1.USER_EMAIL     
  LEFT JOIN FOLLOWERS F2 ON U.EMAIL = F2.FOLLOWER_EMAIL  
  LEFT JOIN SOCIAL_LINKS S ON U.EMAIL = S.USER_EMAIL
GROUP BY 
  U.EMAIL;


-- To get blog details
CREATE VIEW BLOG_PROFILE AS 
SELECT 
  B.ID AS BLOG_ID,
  B.HEADER,
  B.INTRO,
  B.BODY,
  B.USER_EMAIL,
  U.NAME AS 'USER_NAME',
  B.INTRO_IMAGE,
  B.CREATED_ON,
  COUNT(DISTINCT B_L.USER_EMAIL) AS LIKES,
  COUNT(DISTINCT B_C.ID) AS COMMENTS,
  GROUP_CONCAT(DISTINCT S.SEARCH_KEY) AS SEARCH_KEYS,
  GROUP_CONCAT(DISTINCT I.IMAGE_LINK) AS IMAGE_LINKS
FROM 
  BLOGS B 
LEFT JOIN 
  USERS U ON U.EMAIL = B.USER_EMAIL
LEFT JOIN 
  BLOG_IMAGES I ON B.ID = I.BLOG_ID 
LEFT JOIN 
  SEARCH_KEY S ON B.ID = S.BLOG_ID 
LEFT JOIN 
  BLOG_LIKES B_L ON B_L.BLOG_ID = B.ID
LEFT JOIN 
  BLOG_COMMENTS B_C ON B_C.BLOG_ID = B.ID
GROUP BY 
  B.ID;




-- TO GET DETAILS FOR ALL FOLLOWERS OF A USER
CREATE VIEW USER_FOLLOWING AS 
  SELECT 
    F.USER_EMAIL AS 'USER_EMAIL',
    F.FOLLOWER_EMAIL AS 'ALIAS_ID',
    U.NAME AS 'ALIAS_NAME',
    U.PROFILE_PIC AS 'ALIAS_PROFILE_PIC'
  FROM FOLLOWERS F 
  LEFT JOIN USERS U ON F.FOLLOWER_EMAIL = U.EMAIL;

-- TO GET DETAILS FOR ALL FOLLOWED BY USER 
CREATE VIEW FOLLOWED_BY_USER AS 
  SELECT 
    F.FOLLOWER_EMAIL AS 'USER_EMAIL',
    F.USER_EMAIL AS 'ALIAS_EMAIL',
    U.NAME AS 'ALIAS_NAME',
    U.PROFILE_PIC AS 'ALIAS_PROFILE_PIC'
  FROM FOLLOWERS F 
  LEFT JOIN USERS U ON F.USER_EMAIL = U.EMAIL;


